PROGRAM	= woltest
OBJS	= main.o
VPATH	= src

CC	= cc
CCFLAG	= -Wall

RM	= rm -f

.PHONY:	all
all:	$(PROGRAM)

$(PROGRAM):	$(OBJS)
	$(CC) -o $(.TARGET) $(.ALLSRC)

.PHONY:	clean
clean:
	$(RM) $(PROGRAM) $(OBJS)
